#!/usr/bin/env bash
# Inserts new location block using stream editor(sed)

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html

red="location \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}"

sudo sed -i "/server_name _;/a$red" /etc/nginx/sites-available/default

sudo service nginx restart
