#!/usr/bin/env bash
# Inserts new location block using stream editor(sed)

sed -i '/server_name _;/a\
	location \/redirect_me {\
		return 301 http
	}' /etc/nginx/sites-available/default

service nginx restart
