#!/bin/bash

# Configuration for the redirection server block
REDIRECTION_SERVER_BLOCK="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}"

sudo chown -R $USER:$USER /etc/nginx/sites-available

sudo echo -e "$REDIRECTION_SERVER_BLOCK" > /etc/nginx/sites-available/default

sudo systemctl restart nginx

