#!/usr/bin/env bash
# Configures a brand new Ubuntu machine to the requirements asked

sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

sudo chmod 775 /var/www
sudo chmod 775 /var/www/html

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

sudo sed -i "/server_name _;/a\ \n\tlocation \/redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}" /etc/nginx/sites-available/default

sudo sed -i "/location \/ {/,/}/ s/try_files \$uri \$uri\/ =404;/try_files \$uri \$uri\/ =404;\n\t\tadd_header 'X-Served-By' \$hostname;/" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

sudo sed -i "/server_name _;/a\ \n\terror_page 404 /404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}" /etc/nginx/sites-available/default


sudo service nginx restart
