#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

echo -e "\nfrontend jba_frontend\n\tbind *:80\n\tmode http\n\tdefault_backend jba_backend\nbackend jba_backend\n\tbalance roundrobin\n\tserver 237142-web-01 52.91.168.145:80 check\n\tserver 237142-web-02 54.236.17.91:80  check" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
