#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it

sudo mysqldump -u root -p"$1" --databases tyrell_corp > backup.sql
tar -czf $(date +"%d-%m-%Y").tar.gz backup.sql
