#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it

mysqldump -uroot -p"$1" --all-databases 2>/dev/null > backup.sql
tar -czf $(date +"%d-%m-%Y").tar.gz backup.sql
