#!/usr/bin/env bash
# Displays Best School 10 times

minute=0
hour=0

while [ $hour -le 13 ]
do
	if ((minute % 60 == 0)); then
		if [ $hour -eq 13 ]; then
			break
		else
			echo "Hour: $hour"
			((hour++))
		fi
	else
		echo $minute
	fi

	if [ $minute -eq 60 ]; then
		minute=1
		continue
	fi

	((minute++))
done
