#!/usr/bin/env bash
# Displays Best School 10 times

minute=0
hour=0

while [ $hour -le 12 ]
do
	if ((minute % 60 == 0)); then
		echo "Hour: $((minute/60))"
		((hour++))
	else
		echo $minute
	fi

	if [ $minute -eq 60 ]; then
		minute=1
		continue
	fi

	((minute++))
done
