#!/usr/bin/env bash
# Displays content of the current directory



if [ -e "school" ]; then
	echo "school file exists"

	if [ ! -d "school" ] && [ "$(wc -l < "school")" -eq 0 ]; then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi

	if [ -f "school" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
